name: Detect and Trigger Retest
on:
  issue_comment:
    types: [created, edited]

jobs:
  retest:
    runs-on: ubuntu-latest
    steps:
      # Create get run id
      - name: Retest
        if: contains(github.event.comment.body, '/retest')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha}}
        run: |
          echo $OWNER
          echo $REPO
          echo $COMMIT_SHA
          RUNID=$(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs | jq -r '.check_runs[] | select(.name == "CI") | .html_url | capture("/runs/(?<number>[0-9]+)/jobs") | .number' | sed 's/"//g' | head -n 1)
          echo $RUNID
