name: Detect and Trigger Retest
on:
  issue_comment:
    types: [created, edited]

jobs:
  retest:
    runs-on: ubuntu-latest
    steps:
      # Create get run id
      - uses: octokit/request-action@v2.x
        if: contains(github.event.comment.body, '/retest')
        id: create_check_run
        with:
          route: GET /repos/{owner}/{repo}/actions/runs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          workflow_id: ${{ github.event.workflow_id }}
          head: ${{ github.event.issue.pull_request.head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.create_check_run.outputs.data }}'"
