name: Detect and Trigger Retest
on:
  issue_comment:
    types: [created, edited]

jobs:
  retest:
    runs-on: ubuntu-latest
    steps:
      # Create get run id
      - name: Retest
        if: contains(github.event.comment.body, '/retest')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha}}
        run: |
          RUNID=$(gh api repos/$REPO/actions/runs | jq -r '.workflow_runs[] | select(.name == "CI") | .id'| head -n 1)
          echo $RUNID
          echo "latest run is $RUNID"
          gh api --method POST repos/$REPO/actions/runs/$RUNID/rerun-failed-jobs
